// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-Unh_E2ZbL_ll5hIU99Do0XfUZ_w5Mg',
    appId: '1:973633646445:web:21252a3863f5454bdd3464',
    messagingSenderId: '973633646445',
    projectId: 'yatri-mate',
    authDomain: 'yatri-mate.firebaseapp.com',
    storageBucket: 'yatri-mate.firebasestorage.app',
    measurementId: 'G-BBQSHSGSTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcrV7KSlstVDRbgyJzS1dP0SP9qvZqA8',
    appId: '1:973633646445:android:f0740fae6c759e83dd3464',
    messagingSenderId: '973633646445',
    projectId: 'yatri-mate',
    storageBucket: 'yatri-mate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkP0Q0Rk2CfPDQckdFZSk2ZxA672bfWy8',
    appId: '1:973633646445:ios:272e7877b46d0b9cdd3464',
    messagingSenderId: '973633646445',
    projectId: 'yatri-mate',
    storageBucket: 'yatri-mate.firebasestorage.app',
    iosBundleId: 'com.example.travelerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkP0Q0Rk2CfPDQckdFZSk2ZxA672bfWy8',
    appId: '1:973633646445:ios:272e7877b46d0b9cdd3464',
    messagingSenderId: '973633646445',
    projectId: 'yatri-mate',
    storageBucket: 'yatri-mate.firebasestorage.app',
    iosBundleId: 'com.example.travelerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8-Unh_E2ZbL_ll5hIU99Do0XfUZ_w5Mg',
    appId: '1:973633646445:web:22242c76cf2f42e2dd3464',
    messagingSenderId: '973633646445',
    projectId: 'yatri-mate',
    authDomain: 'yatri-mate.firebaseapp.com',
    storageBucket: 'yatri-mate.firebasestorage.app',
    measurementId: 'G-8JX27QFMMG',
  );

}